services:
  vkomari-dev:
    image: kadidalax/vkomari:dev
    container_name: vkomari-dev
    restart: unless-stopped
    ports:
      - "25770:25770"
    volumes:
      - ./data-dev:/app/data
    environment:
      - DB_PATH=/app/data/vkomari.db
      - JWT_SECRET=dev-secret-keep-it-simple
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
